#
# This playbook sets up docker-compose to start the admin web UI
# automatically.
#
---
- hosts: all
  become: true
  tasks:
  - name: Copy in the application jarfile.
    ansible.builtin.copy:
      src: ../target/doorbell-1.0.jar
      dest: /usr/local/bin/doorbell-1.0.jar
  - name: Copy in the doorbell config for systemd so we can start the service.
    ansible.builtin.copy:
      src: doorbell.service
      dest: /lib/systemd/system/doorbell.service
  - name: Enable the admin web UI.
    ansible.builtin.systemd:
      daemon-reload: true
      name: doorbell.service
      enabled: true
      masked: false
      state: restarted
